language: ruby
sudo: required
addons:
  chrome: stable
cache:
  - bundler
notifications:
  email: false
rvm:
  - "2.6"
  - "2.5"
  - "2.4"
  - "jruby-9.1.16.0"
install: bin/setup_ci
before_script:
  - export PATH="$HOME/.nvm/versions/node/v${NODE_JS_VERSION}/bin:$PATH"
script: bin/rake
env:
  global:
    - secure: RbWKxwfpzyQ5uv/jYH68/0J3Y9xe7rQbGULsWZT98FxZcVWLoOFlPPITmnmEK32CjQUww8iMz50FRLxFNmXg8prt1KzpzikVdIZLmYg1NFShI8+JOFhJzwCuk/LLybNUmydejR58FJvV9gS8NYqMh5leFkDM3OwLxhWdcE8hDDQ=
    - NODE_JS_VERSION=7.10.0
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/master.gemfile
