language: ruby
sudo: false
cache:
  - bundler
notifications:
  email: false
rvm:
  - 2.3.0
  - 2.2.2
  - jruby-9.0.3.0
install: bin/setup_ci
before_script:
  - export PATH="$HOME/.nvm/versions/node/v${NODE_JS_VERSION}/bin:$PATH"
script: bin/rake
env:
  global:
    - secure: RbWKxwfpzyQ5uv/jYH68/0J3Y9xe7rQbGULsWZT98FxZcVWLoOFlPPITmnmEK32CjQUww8iMz50FRLxFNmXg8prt1KzpzikVdIZLmYg1NFShI8+JOFhJzwCuk/LLybNUmydejR58FJvV9gS8NYqMh5leFkDM3OwLxhWdcE8hDDQ=
    - NODE_JS_VERSION=7.10.0
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/master.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.3.0
    - gemfile: gemfiles/master.gemfile
